mixinText: |-
  mixin:
    dns:
      enable: true
      ipv6: false
      listen: 0.0.0.0:53
      enhanced-mode: fake-ip #redir-host fake-ip
      nameserver:
         #- 119.29.29.29 # 腾讯DNS
         #- 223.5.5.5 # 阿里DNS
         - 114.114.114.114
         - tls://dns.rubyfish.cn:853
         #- 180.76.76.76 # 百度DNS
         #- 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
         #- 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
         - https://dns.rubyfish.cn/dns-query
      fallback:
         - 114.114.114.114
         # - 1.1.1.1 # Cloudflare DNS
         - tls://dns.rubyfish.cn:853
         #- tls://1.0.0.1:853
         #- tls://dns.google:853
         - https://dns.rubyfish.cn/dns-query

